/** Image prompts recovered from the library file. Preview videos use the compiled template prompt. */
export const LIBRARY_PREVIEW_IMAGE_PROMPTS = {
  "fashion-product-showcase": "Create a premium photorealistic e-commerce fashion product image using the uploaded clothing image as the **exact master reference for the product**.\n\nThe uploaded shirt is the actual product being advertised.\n\nDo not redesign, replace, reinterpret, recolor or modify the shirt. Preserve its exact:\n- color\n- fabric\n- pattern\n- print\n- stitching\n- collar\n- sleeves\n- buttons\n- logo\n- proportions\n- texture\n- distinctive details\n\nPresent the shirt in a premium modern fashion-commerce studio.\n\nShow the shirt in a clean, professionally styled presentation suitable for an online fashion store.\n\nUse a sophisticated neutral studio background with subtle depth and soft shadows.\n\nThe shirt should be the dominant visual subject.\n\nUse realistic fabric folds and physically accurate material texture.\n\nPremium softbox lighting from the front and side.\n\nCreate subtle natural shadows and a realistic floor/surface reflection where appropriate.\n\nThe result should look like a professional e-commerce product campaign photographed for a premium fashion brand.\n\nPhotorealistic fabric.\n\nCrisp details.\n\nNatural colors.\n\nRealistic textile texture.\n\nHigh-end commercial photography.\n\nNo people unless the uploaded reference itself contains a person.\n\nNo additional products.\n\nNo fake logos.\n\nNo invented text.\n\nNo watermark.\n\nVertical 9:16 composition.",
  "restaurant-food-hero": "Create a photorealistic premium restaurant advertisement using the uploaded food/product image as the **master reference**.\n\nThe uploaded food is the exact dish/product that must be advertised.\n\nPreserve the exact appearance, ingredients, colors, shape and presentation of the uploaded food.\n\nDo not replace it with a different dish.\n\nCreate an appetizing premium restaurant environment around the food.\n\nPlace the dish prominently in the center on an elegant restaurant table.\n\nUse warm cinematic restaurant lighting with subtle highlights and realistic shadows.\n\nAdd tasteful supporting ingredients around the dish, but never allow them to replace or visually overpower the main food.\n\nAdd realistic steam rising from hot food where appropriate.\n\nInclude tiny natural moisture highlights and realistic food textures.\n\nCreate a shallow depth of field with the food sharply focused and the restaurant environment softly blurred.\n\nThe result should look like a high-end restaurant campaign photographed for social media and food delivery advertising.\n\nPhotorealistic.\n\nAppetizing.\n\nFresh.\n\nWarm.\n\nPremium.\n\nCinematic.\n\nNo people.\n\nNo fake text.\n\nNo invented branding.\n\nNo watermark.\n\n9:16 vertical composition.",
  "female-product-review": "Create a photorealistic lifestyle image of a confident young adult female content creator reviewing the **exact product shown in the uploaded product image**.\n\n### PRODUCT RULE\n\nThe uploaded image is the authoritative reference for the product.\n\nWhatever product is uploaded \u2014 mobile phone, shirt, perfume, watch, cosmetic, gadget, accessory, food product or any other physical product \u2014 use that exact product.\n\nDo not invent a different product.\n\nDo not redesign it.\n\nPreserve its exact:\n- shape\n- color\n- material\n- branding\n- logo\n- proportions\n- distinctive physical details\n\nThe woman should naturally hold, wear, demonstrate or interact with the product according to what the product is.\n\nExamples:\n\n- phone \u2192 hold it and demonstrate it\n- shirt \u2192 wear it naturally\n- perfume \u2192 hold the bottle and present it\n- watch \u2192 wear it on the wrist\n- headphones \u2192 wear or demonstrate them\n- cosmetic \u2192 hold and demonstrate the packaging\n- food product \u2192 hold and present the package\n\nCreate a modern lifestyle environment suitable for a social-media product review.\n\nThe creator looks natural, friendly and authentic rather than overly posed.\n\nUse realistic skin texture, natural expression and believable hand positioning.\n\nCreate professional creator-style lighting.\n\nThe product and creator should both be clearly visible.\n\nPhotorealistic.\n\nModern UGC aesthetic.\n\nHigh-quality smartphone-camera / creator-camera look.\n\nVertical 9:16.\n\nNo watermark.\n\nNo random text.\n\nNo fake product.",
  "perfume-advertisement": "Create a photorealistic premium luxury perfume product for a fragrance brand named **MOV**.\n\nDesign a sophisticated, elegant and modern perfume bottle with a transparent premium glass body filled with beautiful **light blue / icy-blue liquid**.\n\nThe liquid should appear fresh, clean and luxurious, with realistic transparency, subtle refraction and natural internal reflections.\n\nThe bottle should have a distinctive high-end fragrance silhouette that looks like a real commercially manufactured luxury perfume bottle.\n\nThe brand name **\u201cMOV\u201d** must be clearly and accurately displayed on the front of the bottle as the primary branding.\n\nThe word must be spelled exactly:\n\n**MOV**\n\nUse refined minimalist luxury typography.\n\nUse a sophisticated premium cap, preferably polished silver, chrome, transparent crystal or another elegant material that complements the light-blue liquid.\n\nPlace the MOV perfume bottle upright in the exact center.\n\nCreate a luxurious refreshing environment inspired by fresh blue water and tropical citrus freshness.\n\nUse an icy-blue, aqua, turquoise and subtle green-blue gradient background.\n\nPlace the bottle on a glossy reflective surface.\n\nSurround the scene with fresh citrus and tropical fruits such as lemon, lime, grapefruit, orange, blueberries and other refreshing fruits.\n\nThe fruits should look fresh, juicy, vibrant and photorealistic, with visible moisture droplets.\n\nUse premium cinematic fragrance advertising lighting.\n\nSoft diffused front light.\n\nSubtle blue and aqua rim lighting.\n\nRealistic glass highlights.\n\nRealistic liquid refraction.\n\nPhotorealistic.\n\nUltra-realistic glass and liquid.\n\nFresh and refreshing.\n\nPremium luxury fragrance campaign.\n\nNo additional words.\n\nNo random letters.\n\nNo extra logos.\n\nNo watermark.\n\nNo people.\n\nNo duplicate bottles.\n\nVertical 9:16.",
} as const;

export const LIBRARY_PREVIEW_TEMPLATE_IDS = [
  "fashion-product-showcase",
  "restaurant-food-hero",
  "female-product-review",
  "perfume-advertisement",
] as const;

/** Example stills for launch templates that do not yet have a verified preview. */
export const REMAINDER_PREVIEW_IMAGE_PROMPTS = {
  "phone-floating-ad": "Create one premium example smartphone floating upright in a futuristic gradient studio. The phone is a generic unbranded device with a clean empty screen, no logo, no readable text, and no people. Subtle particles, soft rim light, vertical 9:16, photorealistic.",
  "food-delivery-ad": "Create one premium example restaurant meal in plain delivery packaging on a modern tabletop. The dish is generic, appetizing, and unbranded. No logo, no readable text, no people, warm light, vertical 9:16, photorealistic.",
  "luxury-fashion-reveal": "Create one premium example black luxury garment on a reflective floor in a black studio under a focused spotlight. The garment is generic, with no logo, no readable text, and no people. High contrast, vertical 9:16, photorealistic.",
  "cosmetic-product-commercial": "Create one premium example cosmetic bottle standing upright in a soft beige beauty studio. The package is generic, with no brand name, no readable label text, and no people. Fine light reflections, vertical 9:16, photorealistic.",
  "real-estate-property": "Create one premium example modern villa exterior in natural daylight. Accurate simple architecture, no people, no cars with readable plates, no address text, no signage. Vertical 9:16, photorealistic.",
  "business-service-promotion": "Create one premium example blank service card centered in a modern professional studio. The card is a clean abstract gradient with no letters, numbers, logos, or interface text. No people. Vertical 9:16, photorealistic.",
} as const;

export const REMAINDER_PREVIEW_TEMPLATE_IDS = [
  "phone-floating-ad",
  "food-delivery-ad",
  "luxury-fashion-reveal",
  "cosmetic-product-commercial",
  "real-estate-property",
  "business-service-promotion",
] as const;
